server:
  port: 8050
eureka:
  client:
    serviceUrl:
      defaultZone=http://localhost:8761/eureka/:

zuul:
  routes:
    customer:
      url: http://localhost:7744
    accounts:
      url: http://localhost:7779, http://localhost:7778
    cards:
      url: http://localhost:7711